name: Galaxy Actions
on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validation
        uses: gradle/wrapper-validation-action@v1

      - name: JDK
        uses: actions/setup-java@v1
        with:
          java-version: '15'

      - name: cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle/loom-cache
          key: caches-${{ hashFiles('build.gradle.kts', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            caches-

      - name: Build
        run: ./gradlew --no-daemon build

      - name: Upload-Artifact
        uses: actions/upload-artifact@master
        with:
          name: jar
          path: build/libs/*.jar
